# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'mvn package -Pproduction' # runs during prebuild
    command: echo 'mvn'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview


vscode:
  extensions:
    - runem.lit-plugin@1.2.1:llHUlx8TJ6tFKGa1t6dpLQ==
    - vscjava.vscode-java-test@0.27.0:gNh98vNbqtZC6ydHasFxAQ==
    - pivotal.vscode-spring-boot@1.23.0:1iLvjTfznJrV611qRUeOHg==